CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,47 +6,47 @@ permissions:
   actions: read
   checks: write
 jobs:
-  build-test:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4         # Checkout the repository
+#  build-test:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4         # Checkout the repository
+#
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: 'temurin'
+#          java-version: '17'
+#
+#      - name: Grant execute permissions for Gradle
+#        run: chmod +x gradlew
+#
+#      - name: Run Kotlin tests
+#        run: ./gradlew test                # Run Kotlin tests
+#
+#      - uses: actions/upload-artifact@v4
+#        if: success() || failure()
+#        with:
+#          name: kotlin-test-results
+#          path: build/test-results/
+#
+#  report:
+#    runs-on: ubuntu-latest
+#    needs: build-test
+#    steps:
+#      - uses: actions/checkout@v4         # Checkout the repository
+#
+#      - uses: actions/download-artifact@v4
+#        with:
+#          name: kotlin-test-results
+#
+#      - uses: dorny/test-reporter@v1
+#        with:
+#          artifact: kotlin-test-results
+#          name: Test Report
+#          path: 'test/*.xml'
+#          reporter: java-junit
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: '17'
-
-      - name: Grant execute permissions for Gradle
-        run: chmod +x gradlew
-
-      - name: Run Kotlin tests
-        run: ./gradlew test                # Run Kotlin tests
-
-      - uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: kotlin-test-results
-          path: build/test-results/
-
-  report:
-    runs-on: ubuntu-latest
-    needs: build-test
-    steps:
-      - uses: actions/checkout@v4         # Checkout the repository
-
-      - uses: actions/download-artifact@v4
-        with:
-          name: kotlin-test-results
-
-      - uses: dorny/test-reporter@v1
-        with:
-          artifact: kotlin-test-results
-          name: Test Report
-          path: 'test/*.xml'
-          reporter: java-junit
-
-  build:
+  build-kover:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -54,9 +54,10 @@ jobs:
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
-          java-version: '17'
-      - name: Set up Gradle
-        uses: gradle/actions/setup-gradle@v3
+          java-version: '21'
+
+      - name: Grant execute permissions for Gradle
+        run: chmod +x gradlew
 
       - name: Generate kover coverage report
         run: ./gradlew koverXmlReport
